-- Active: 1770455450205@@localhost@9000@product_db

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    category TEXT,
    price NUMERIC(10, 2) NOT NULL,
    stock_quantity INT NOT NULL,
    is_available BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_method VARCHAR(50) NOT NULL,
    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE CASCADE
);

SELECT * FROM products;
SELECT * FROM orders;

SELECT * FROM orders o INNER JOIN products p 
ON o.product_id = p.product_id; -- Joining orders and products to get combined information about orders and their corresponding products

SELECT o.order_id, o.product_id, p.product_name, p.price
FROM orders o INNER JOIN products p 
ON o.product_id = p.product_id; -- Selecting specific columns from the joined tables to get order details along with product name and price

SELECT p.product_name, o.order_id
FROM  products p LEFT JOIN orders o 
ON o.product_id = p.product_id; -- Performing a left join to get all products along with their corresponding order IDs, if any. This will include products that have not been ordered (with NULL order_id).

SELECT o.order_id, p.product_name, p.category
FROM 
orders o  JOIN products p 
ON o.product_id = p.product_id
WHERE p.category = 'Electronics'; -- Joining orders and products to get order details for products in the 'Electronics' category. This will filter the results to only include orders for electronic products.

SELECT o.order_id, p.product_name, p.price
FROM orders o 
JOIN products p 
ON o.product_id = p.product_id
ORDER BY p.price DESC; -- Joining orders and products to get order details along with product price, and sorting the results by price in descending order to show the most expensive products first.

SELECT p.product_name, COUNT(o.order_id) AS total_orders
FROM 
products p 
LEFT JOIN orders o ON p.product_id = o.product_id
GROUP BY p.product_name; -- Performing a left join to get all products along with the count of orders for each product. This will show the total number of orders for each product, including those that have not been ordered (with a count of 0). The results are grouped by product name to aggregate the order counts.

SELECT p.product_name, SUM(o.quantity * p.price) AS total_revenue
FROM products p 
JOIN orders o ON p.product_id = o.product_id
GROUP BY p.product_name; -- Joining products and orders to calculate the total revenue generated by each product. This is done by multiplying the quantity of each order by the price of the product and summing it up for each product. The results are grouped by product name to get the total revenue for each product.


SELECT p.product_name, SUM(o.quantity * p.price) AS total_revenue
FROM products p 
JOIN orders o ON p.product_id = o.product_id
GROUP BY p.product_name
HAVING SUM(o.quantity * p.price) > 2000; -- Filtering the results to only include products that have generated more than 1000 in total revenue.

